CREATE TABLE IF NOT EXISTS product_aliases (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), alias_name TEXT NOT NULL, canonical_name TEXT NOT NULL, similarity_score NUMERIC, created_at TIMESTAMPTZ DEFAULT NOW()); ALTER TABLE product_aliases ENABLE ROW LEVEL SECURITY; CREATE POLICY "Allow read" ON product_aliases FOR SELECT USING (true); CREATE POLICY "Allow insert" ON product_aliases FOR INSERT WITH CHECK (true);

INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('TAGLIATA DI BOVINO ADULTO', 'HAMBURGER DI BOVINO ADULTO', 0.75);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('TRIPPA DI BOVINO ADULTO', 'HAMBURGER DI BOVINO ADULTO', 0.73);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('STRACCETTI DI BOVINO ADULTO', 'HAMBURGER DI BOVINO ADULTO', 0.72);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('ARROSTO SCELTO DI BOVINO ADULTO', 'HAMBURGER DI BOVINO ADULTO', 0.70);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('SPEZZATINO DI BOVINO ADULTO', 'HAMBURGER DI BOVINO ADULTO', 0.68);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('MOZZARELLA TRIS SANTA LUCIA GALBANI', 'MOZZARELLA TRIS SANTA LUCIA', 0.87);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('MOZZARELLA SANTA LUCIA GALBANI', 'MOZZARELLA TRIS SANTA LUCIA', 0.77);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('BIRAGHINI GRAN BIRAGHI', 'BIRAGHINI BIRAGHI', 0.87);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('SNACK BIRAGHINI BIRAGHI', 'BIRAGHINI BIRAGHI', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('BI-SNACK BIRAGHINO CON CARALLI BIRAGHI', 'BIRAGHINI BIRAGHI', 0.62);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PASTA DI SEMOLA BARILLA', 'PASTA DI SEMOLA', 0.79);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PASTA DI SEMOLA VOIELLO', 'PASTA DI SEMOLA', 0.79);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PASTA DI SEMOLA CORTICELLA', 'PASTA DI SEMOLA', 0.73);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PASTA DI SEMOLA FORMATI NORMALI', 'PASTA DI SEMOLA', 0.65);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PASTA DE SEMOLA INTEGRALE BARILLA', 'PASTA DI SEMOLA', 0.58);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PASTA FRESCA SFOGLIA', 'PASTA SFOGLIA', 0.79);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PASTA SFOGLIA STUFFER', 'PASTA SFOGLIA', 0.76);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PASTA SFOGLIA ROTONDA', 'PASTA SFOGLIA', 0.76);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PASTA SFOGLIA VEGETALE STUFFER', 'PASTA SFOGLIA', 0.60);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PASTA FRESCA RIPIENA', 'PASTA SFOGLIA', 0.55);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('WÜRSTEL MISTO', 'WÜRSTEL', 0.70);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('GORGONZOLA DOP BIG IOOR', 'GORGONZOLA DOP DOLCE', 0.74);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('GORGONZOLA DOP DOLCE GIM INVERNIZZI', 'GORGONZOLA DOP DOLCE', 0.73);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('GORGONZOLA DOP E MASCARPONE', 'GORGONZOLA DOP DOLCE', 0.72);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('SPUNTI SIMMENTHAL', 'SIMMENTHAL', 0.74);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('BIRRA PERONI LAGER', 'BIRRA PERONI', 0.80);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PESCHE PARAGUAY GIALLE', 'PESCHE GIALLE', 0.74);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PESCHE BIANCHE', 'PESCHE GIALLE', 0.74);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PESCHE NETTARINE GIALLE', 'PESCHE GIALLE', 0.72);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('GNOCCHI ALLA ROMANA', 'GNOCCHI ALLA RUCOLA', 0.84);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('GNOCCHI ALLA BARBABIETOLA', 'GNOCCHI ALLA RUCOLA', 0.77);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('CARTA IGIENICA CLASSICA', 'CANDEGGINA CLASSICA', 0.71);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('CARTA IGIENICA BRAVO', 'CANDEGGINA CLASSICA', 0.41);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('CARTA IGIENICA LALYNEA', 'CANDEGGINA CLASSICA', 0.39);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('CARTA IGIENICA THAT''S AMORE', 'CANDEGGINA CLASSICA', 0.35);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('CARTA IGIENICA FAMILY SCOTTEX', 'CANDEGGINA CLASSICA', 0.33);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('SPUGNE VILEDA', 'SPUGNA VILEDA', 0.92);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('GRANA PADANO DOP GRATTUGIATO FRESCO', 'GRAN BIRAGHI GRATTUGGIATO FRESCO', 0.75);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('GRANMIX CUCINA GRATTUGIATO FRESCO FERRARI', 'GRAN BIRAGHI GRATTUGGIATO FRESCO', 0.71);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('GRANA PADANO RISERVA DOP GRATTUGIATO FRESCO FERRARI', 'GRAN BIRAGHI GRATTUGGIATO FRESCO', 0.65);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('BOCCONCINI DI MOZZARELLA FIOR DI LATTE', 'MOZZARELLA FIOR DI LATTE', 0.77);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('POLPA PRONTA DI POMODORO', 'POLPA DI POMODORO', 0.83);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('LA PASSATA DI POMODORO', 'POLPA DI POMODORO', 0.72);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PASSATA DI POMODORO MUTTI', 'POLPA DI POMODORO', 0.67);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PASSATA DI POMODORO AGRONMENTE', 'POLPA DI POMODORO', 0.60);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('DEODORANTE NIVEA', 'DEODORANTE DOVE', 0.84);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('DEODORANTE ROLL-ON DOVE', 'DEODORANTE DOVE', 0.79);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('SUGO ALLO SCOGLIO APPETTAIS', 'SUGO SCOGLIO APPETAIS', 0.88);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('SUGO ALLA MARINARA APPETAIS', 'SUGO SCOGLIO APPETAIS', 0.67);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PROSCIUTTO CRUDO NAZIONALE', 'PROSCIUTTO CRUDO', 0.76);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PROSCIUTTO DI PARMA DOP', 'PROSCIUTTO CRUDO', 0.72);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PROSCIUTTO CRUDO DI PARMA DOP', 'PROSCIUTTO CRUDO', 0.71);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PROSCIUTTO CRUDO SAN DANIELE DOP', 'PROSCIUTTO CRUDO', 0.67);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PROSCIUTTO SAN DANIELE DOP', 'PROSCIUTTO CRUDO', 0.62);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('SALVIETTE BABY FRESH', 'SALVIETTE BABY', 0.82);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('SALVIETTE BABY FRESH POP-UP', 'SALVIETTE BABY', 0.68);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('SALVIETTE BABY CON COPERCHIO', 'SALVIETTE BABY', 0.67);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('FORMAGGINI BEL PAESE GALBANI', 'BEL PAESE GALBANI', 0.76);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('4 UOVA FRESCHE', 'UOVA FRESCHE GRANDI', 0.73);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('CAFFÈ CREMA E GUSTO LAVAZZA CLASSICO', 'CAFFÈ CREMA E GUSTO LAVAZZA', 0.86);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('KRAPFEN ALLA CREMA', 'KRAPFEN CREMA', 0.84);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('CRACKERS COLUSSI SALATI', 'CRACKERS COLUSSI', 0.82);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('POMODORI PERINO INSALATARI', 'POMODORI PERINI INSALATARI', 0.96);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('POMODORI PERINI DA INSALATA', 'POMODORI PERINI INSALATARI', 0.91);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('SUCCO DI FRUTTA', 'SUCCO DI MELA', 0.71);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('SUCCO E POLPA DI FRUTTA', 'SUCCO DI MELA', 0.56);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('POLPA DI FRUTTA', 'SUCCO DI MELA', 0.43);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('BISCOTTI ZUPPALATTE COLUSSI', 'ZUPPALATTE COLUSSI', 0.80);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('BISCOTTI COLUSSI', 'ZUPPALATTE COLUSSI', 0.59);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('BISCOTTI COLUSSI ZUPPALLETTE', 'ZUPPALATTE COLUSSI', 0.43);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('BISCOTTI CLASSICI', 'ZUPPALATTE COLUSSI', 0.29);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('IL FRESCO SPALHABILES NONNO NANNI', 'IL FRESCO SPALMABILE NONNO NANNI', 0.95);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('LINEA GLISS SCHWARZKOPF', 'GLISS SCHWARZKOPF', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('DETERGENTE SPRAY', 'DETERGENTE', 0.77);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('DETERGENTE INTIMO', 'DETERGENTE', 0.74);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('DETERGENTE VALIDO', 'DETERGENTE', 0.74);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('DETERGENTE CHANTE CLAIR', 'DETERGENTE', 0.61);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('DETERGENTE INTIMO NEUTROMED', 'DETERGENTE', 0.54);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('OLIO EXTRA VERGINE DI OLIVA DANTE', 'OLIO EXTRAVERGINE DI OLIVA DANTE', 0.98);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('OLIO EXTRA VERGINE DI OLIVA BIO DANTE', 'OLIO EXTRAVERGINE DI OLIVA DANTE', 0.93);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('OLIO EXTRA VERGINE DI OLIVA MOROSO BIFTI', 'OLIO EXTRAVERGINE DI OLIVA DANTE', 0.78);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('FILETTI DI SGOMBRO ANGELO PARODI', 'FILETTI DI SGOMBRO DELICIUS', 0.75);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('FILETTI DI ALICI DISTESE DELICIUS', 'FILETTI DI SGOMBRO DELICIUS', 0.70);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('FILETTI DI ALICI DELICIUS PIZZA', 'FILETTI DI SGOMBRO DELICIUS', 0.69);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('FILETTI DI ALICI IN OLIO DI OLIVA DELICIUS', 'FILETTI DI SGOMBRO DELICIUS', 0.64);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('FILETTI DI ALICI L''OLIO DI OLIVA DELICATESSEN', 'FILETTI DI SGOMBRO DELICIUS', 0.56);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('TEGLIA PER PIZZA IN ACCIAIO ALPINA', 'PALA PER PIZZA IN ACCIAIO ALPINA', 0.91);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('INSALATA DI MARE', 'INSALATA KOMETE', 0.71);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('VASCHETTA IN ALLUMINIO CON COPPERCHIO DOMO PAK', 'VASCHETTE IN CARTONCINO CON COPPERCHI CUKI', 0.73);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('LATTE UHT PARZIALMENTE SCREMATO', 'LATTE UNH PARZIALMENTE SCREMATO', 0.97);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('LATTE UHT CANNABIS PARZIALMENTE SCREMATO', 'LATTE UNH PARZIALMENTE SCREMATO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('T OVAGLIOLI BRAVO', 'TONAGIOLI BRAVO', 0.88);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('BURGER VEGETARIANO', 'BURGER VEGETALE', 0.79);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('2 BURGER VEGETALI VALSOIA', 'BURGER VEGETALE', 0.70);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('BISTECCHINE DI MARE TIKO', 'BISTECHINE DI MARE', 0.86);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PESTO ALLA GENOVESE SACLÀ', 'PESTO ALLA GENOVESE BARILLA', 0.88);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('BRESAOLA DI TACCHINO RIGAMONTI', 'BRESAOLA DI TACCHINO', 0.80);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('BRESAOLA PUNTA D''ANCA IGP RIGAMONTI', 'BRESAOLA DI TACCHINO', 0.51);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('BRESAOLA VALTELLINA IGP RIGAMONTI', 'BRESAOLA DI TACCHINO', 0.49);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('CARPACCIO DI BRESAOLA PUNTA D''ANCA', 'BRESAOLA DI TACCHINO', 0.44);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('CARPACCIO DI BRESAOLA PUNTA D''ANCA RIGAMONTI', 'BRESAOLA DI TACCHINO', 0.44);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('TARTINE SALMONE E GAMBERETTI', 'TARTINE SALMONE E GAMBERI', 0.94);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('STRACCHINO INVERNIZZINA INVERNIZZI', 'INVERNIZZINA INVERNIZZI', 0.81);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('ZUPPA PRONTA KNORR', 'VELLUTATA PRONTA KNORR', 0.75);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PIATTI PRONTI KNORR', 'VELLUTATA PRONTA KNORR', 0.68);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PIATTI PRONTI MINESTRONE KNORR', 'VELLUTATA PRONTA KNORR', 0.54);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('KETCHUP TOP DOWN CALVÉ', 'KETCHUP CALVÉ', 0.74);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PHILADELPHIA LIGHT', 'PHILADELPHIA CLASSICO', 0.77);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PHILADELPHIA ORIGINAL', 'PHILADELPHIA CLASSICO', 0.67);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('DETERSIPI PIATTI CIF', 'DETERSIVO PER PIATTI', 0.75);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('DETERSIVO PER BUCATO ARIETE', 'DETERSIVO PER PIATTI', 0.72);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('TOVAGLIOLI DOPPIO VELO', 'TOVAGLIOLI DECORATI EVERY', 0.72);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('CUORI DI MERLUZZO', 'CUORI DI NASELLO', 0.73);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('FILETTI DI MERLUZZO', 'CUORI DI NASELLO', 0.46);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('FILETTI DI SALMONE', 'CUORI DI NASELLO', 0.41);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('FILETTI DI MERLUZZO ALASKA', 'CUORI DI NASELLO', 0.33);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('LA MINI PINSA ROMANA L''ARTIGIANO', 'LA MINI PINSA ROMANA', 0.77);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('MAIONESE CALVÉ CLASSICA', 'MAIONESE CALVÉ', 0.76);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('MAIONESE CLASSICA CALVÉ', 'MAIONESE CALVÉ', 0.76);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('MAIONESE BIOLOGICA BIFI', 'MAIONESE BIFFI', 0.70);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('ROBIOLA NONNO NANNI', 'BURRATA NONNO NANNI', 0.74);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('STRACCIATELLA NONNO NANNI', 'BURRATA NONNO NANNI', 0.73);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('STRACCHINO NONNO NANNI', 'BURRATA NONNO NANNI', 0.68);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('SACCO PRATICO VIROSAC', 'SACCO RIFIUTI VIROSAC', 0.81);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('CIOCCOLATI NOVI', 'CIOCCOLATO NOVIPÙ', 0.88);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('SHAMPOO ULTRADOLCE GARNIER', 'ULTRADOLCE GARNIER', 0.82);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('SHAMPOO FRUCTIS GARNIER', 'ULTRADOLCE GARNIER', 0.49);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('CRENA VEGETALE DA CUCINA', 'CREMA VEGETALE DA CUCINA', 0.96);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('LATTE UHT ACCADI SENZA LATTOSIO GRANAROLO', 'LATTE UMM SENZA LATTOSIO ACCADI GRANAROLO', 0.78);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('TÈ VERDE TWININGS', 'TÈ TWININGS', 0.79);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('BENESSERE TWININGS', 'TÈ TWININGS', 0.69);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('COTECHINO COTTO DI MODENA IGP', 'COTECHINO COTTO MODENA IGP', 0.95);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('GRIGLIA PRONTA PER BARBECUE RAPIDO', 'GRIGLIA PER BARBECUE', 0.74);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('IL DADO KNORR VEGETALE', 'DADO KNORR VEGETALE-CLASSICO', 0.76);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('LIQUIDO PER LAVATRICE CHANTE CLAIR', 'LIQUIDO LAVATRICE DIXAN CLASSICO', 0.76);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('SFILACCI DI BRESSOLA VIAGGIO NEL GUSTO', 'SULACCI DI BRESCİA VIAGGIO NEL GUSTO', 0.89);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('FORMAGGIO GRECO MERAKI', 'FORMAGGIO GRECO', 0.81);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('AMMORBIDENTE CONCENTRATO VERNEL', 'AMMORBIDENTE I CONCENTRATI', 0.81);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('AMMORBIDENTE CONCENTRATO FELZE AZZURRA', 'AMMORBIDENTE I CONCENTRATI', 0.72);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('AMMORBIDENTE CONCENTRATO FELCE AZZURRA', 'AMMORBIDENTE I CONCENTRATI', 0.72);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('BONARDA OLTREPRO PAVESE DOC LE ROVOLE', 'BONARDA DELL''OLTREPO PAVESE DOC', 0.76);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('COCA COLA CLASSICO ZERO', 'COCA COLA CLASSICA', 0.83);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('COCA COLA CLASSICA, ZERO FANTA CLASSICA', 'COCA COLA CLASSICA', 0.63);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('COCA COLA CLASSICA, COCA COLA ZERO, SPRITE', 'COCA COLA CLASSICA', 0.60);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('GAMBERI ARGENTINI SELVAGGI', 'GAMBERI ARGENTINI SQUASCIATI', 0.78);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('L''ACCHIAPPACOLORI GREY', 'L''ACCHIAPPACOLORE GREY', 0.95);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('GAMBERO INDOPACIFICO SGUSCIATO', 'GAMBERO INDOPACIFICO SGUCCIATO', 0.97);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('BISCOTTI ZERO-PIÙ BALOCCO', 'BISCOTTI BALOCCO', 0.78);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('BURRO BIO PARMAREGGIO', 'BURRO PARMAREGGIO', 0.89);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PRIMI PRONTI LASAGNE CANNELLONI MELANZANE', 'PRIMI PRONTI LASAGNE, CANNELLONI, MELANZANE', 0.98);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('FAGOLOSI GRISSIN BON CLASSICI', 'FAGOLOSI GRISSIN BON', 0.82);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('TOVAGLIA COLORI ASSORTITI', 'GHIACCIOLI ASSORTITI', 0.76);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('POMODORI DATTERINO CASSETTA', 'POMODORI DATTERINO', 0.80);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('POMODORINI DATTERINO TRIPFOGLIO', 'POMODORI DATTERINO', 0.73);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('STELI GUSTOSI MIORTO', 'STELI GUSTOSI MIOORTO', 0.98);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('TAVOGLIOLI', 'TOVAGLIOLI', 0.80);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('GRAN COPPA FAMIGLIA TOMRITTO', 'MINI COPPA FAMIGLIA TOMITTO', 0.87);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('GRAN COPPA FAMIGLIA TONITTO', 'MINI COPPA FAMIGLIA TOMITTO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('FAZZOLETTI SCOTTEX', 'FAZZOLETTI', 0.71);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('LATTE UHT INTERO', 'LATTE UHT', 0.72);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('SALSICCIA DI MAIALE', 'SALSICCIA PICCANTE', 0.70);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('10 HAMBURGER', '4 HAMBURGER', 0.87);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PROSCIUTTO COTTO DI ALTA QUALITÀ ROVAGNATI', 'PROSCIUTTO COTTO ALTA QUALITÀ', 0.82);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PROSCIUTTO COTTO ALTA QUALITÀ NAZIONALE LENTI', 'PROSCIUTTO COTTO ALTA QUALITÀ', 0.78);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PROSCIUTTO COTTO ALTA QUALITÀ RICCAFETTA RASPINI', 'PROSCIUTTO COTTO ALTA QUALITÀ', 0.75);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('FRIGGI TOPAZIO', 'FRIGGÌ TOPAZIO', 1.00);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('DENTIFRICIO AZ', 'DENTIFRICIO AQUAFRESH', 0.74);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('DENTIFRICIO TRIPLA PROTEZIONE AQUAFRESH', 'DENTIFRICIO AQUAFRESH', 0.70);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('BOCCONCINI RIPIENI VALLELATA', 'BOCCONCINI IN SALSA', 0.72);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('ACQUA NATURALE VALMORA', 'ACQUA NATURALE SANT''ANNA', 0.74);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('BISCOTTI MULINO BIANCO', 'BAIOCCHI MULINO BIANCO', 0.82);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('NASTRINE MULINO BIANCO', 'BAIOCCHI MULINO BIANCO', 0.73);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('IL CORNETTO MULINO BIANCO', 'BAIOCCHI MULINO BIANCO', 0.68);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('LIGNINO OMINO BIANCO', 'BAIOCCHI MULINO BIANCO', 0.67);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PIADELLE TOAST MULINO BIANCO', 'BAIOCCHI MULINO BIANCO', 0.64);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('LINEA ZUPPE KOME TE', 'ZUPPE KOME TE', 0.81);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('CIBO PER CANI PRIMIUM', 'CROCCHETTE PER CANI PRIMIUM', 0.79);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PIZZA MARGHERITA APPETAIS', 'PIZZA MARGHERITA', 0.78);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('SALAME GENTILE DELLA ROSA GRAN CRUDO', 'SALAME GENTILE DELLA ROSA', 0.82);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('FILETTI DI TONNO MAREBLU', 'FILETTI DI TONNO MARUZELLA', 0.84);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('FILETTI DI TONNO NOSTROMO', 'FILETTI DI TONNO MARUZELLA', 0.71);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('TRANCETTI DI TONNO RIO MARE', 'FILETTI DI TONNO MARUZELLA', 0.68);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('BIETA ERBETTA A CUBETTI', 'BIETA ERBETTA', 0.72);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('ASCIUGUTUTTO', 'ASCIUGATUTTO', 0.92);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('ASCIUGATUTTO CHRISTMAS', 'ASCIUGATUTTO', 0.71);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('SALSA AMADORI DIVERSI TIPI', 'QUASAR DIVERSI TIPI', 0.71);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('SALUMI EKOM DIVERSI TIPI', 'QUASAR DIVERSI TIPI', 0.70);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('CONFETTURA DI FRUTTA VIRTÙ BIO OROGEL', 'CONFETTURA VIRTU DI FRUTTA BIO OREGEL', 0.81);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('LATTE UHT ALTA DIGERIBILITÀ ZYMIL PARMALAT', 'LATTE LITE ALTA DIGERIBILITA CANDIA', 0.73);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('LATTE UHT ALTA DIGERIBILITÀ SENZA LATTOSIO ZYMIL PARMALAT', 'LATTE LITE ALTA DIGERIBILITA CANDIA', 0.63);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('TOVAGLIOLI MONOVELO SCOTTEX', 'TAVOGLIOLI MONOVELO BRAVO', 0.73);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('FRUTTA SECCA E SNACK KOME TE', 'FRUTTA SECCA SGUSCIATA KOME TE', 0.79);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('CHE SQU'' DI BIFFI', 'CHE SUGO! BIFFI', 0.75);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('DETERSIVO LAVATRICE SPUMA E CAMPAGNA MARSIGLIA', 'DETERGIVO LAVATRICE MARSIGLIA', 0.75);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('DETERSIVO LAVATRICE SPUMA DI SCIAMPAGNA MARSIGLIA', 'DETERGIVO LAVATRICE MARSIGLIA', 0.72);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('SORBETTO AL LIMONE', 'SORBETTO LIMONE TONITTO', 0.73);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('VINO BIANCO ROSSO', 'VINO ROSSO', 0.74);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('VINO BIANCO BRIK', 'VINO ROSSO', 0.46);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('BURRATA DI BUFALA PONTE REALE', 'BURRATA DI BUFALA', 0.74);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('DOLCETTO DI OVADA DOC', 'DOLCETTO D''ACQUI DOC', 0.73);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('BIRRA VAN PUR EXTRA STRONG', 'BIRRA KUMPEL ULTRA STRONG', 0.71);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('ICE 3 CUP', 'ICE CUP', 0.88);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('SALUMI SENFTER', 'SALLUMI SENETER', 0.90);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('SPECK ALTO ADIGE IGP', 'SPECK DELL''ALTO ADIGE IGP', 0.89);
