-- ML-Generated Product Aliases
CREATE TABLE IF NOT EXISTS product_aliases (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), alias_name TEXT NOT NULL, canonical_name TEXT NOT NULL, similarity_score NUMERIC, created_at TIMESTAMPTZ DEFAULT NOW()); ALTER TABLE product_aliases ENABLE ROW LEVEL SECURITY; CREATE POLICY "Allow read" ON product_aliases FOR SELECT USING (true); CREATE POLICY "Allow insert" ON product_aliases FOR INSERT WITH CHECK (true);

INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('10 HAMBURGER', '4 HAMBURGER', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('4 HAMBURGER AMICA NATURA', '4 HAMBURGER', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('2 BURGER VEGETALI VALSOIA', 'BURGER VEGETALE', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('BURGER 100% VEGETALE UNCONVENTIONAL', 'BURGER VEGETALE', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('BURGER VEGETARIANO', 'BURGER VEGETALE', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('6 UOVA FRESCHE LE PIEMONTESE', '4 UOVA FRESCHE', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('UOVA FRESCHE GRANDI', '4 UOVA FRESCHE', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('ACQUA NATURALE SANT''ANNA', 'ACQUA NATURALE VALMORA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('ACQUA VALMORA NATURALE', 'ACQUA NATURALE VALMORA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('CORTESE DEL PIEMONTE DOC', 'ALBAROSSA PIEMONTE DOC', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('VASCHETTA IN ALLUMINIO CON COPPERCHIO DOMO PAK', 'ALLUMINIO DOMO PAK', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('ALVEARI BURRO SALATO E MIELE MULINO BIANCO', 'BAIOCCHI MULINO BIANCO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('BISCOTTI MULINO BIANCO', 'BAIOCCHI MULINO BIANCO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('CUOR DI PANE MULINO BIANCO', 'BAIOCCHI MULINO BIANCO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('FETTE BISCOTTATE MULINO BIANCO', 'BAIOCCHI MULINO BIANCO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('FROLLINI RIPIENI MULINO BIANCO', 'BAIOCCHI MULINO BIANCO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('IL CORNETTO MULINO BIANCO', 'BAIOCCHI MULINO BIANCO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('NASTRINE MULINO BIANCO', 'BAIOCCHI MULINO BIANCO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PIADELLE TOAST MULINO BIANCO', 'BAIOCCHI MULINO BIANCO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PLUM CAKE MULINO BIANCO CLASSICO', 'BAIOCCHI MULINO BIANCO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('AMMORBIDENTE CONCENTRATO FELCE AZZURRA', 'AMMORBIDENTE I CONCENTRATI', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('AMMORBIDENTE CONCENTRATO FELZE AZZURRA', 'AMMORBIDENTE I CONCENTRATI', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('AMMORBIDENTE CONCENTRATO SPUMA DI SCIAMPAGNA', 'AMMORBIDENTE I CONCENTRATI', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('AMMORBIDENTE CONCENTRATO VERNEL', 'AMMORBIDENTE I CONCENTRATI', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('AMMORBIDENTE PROFUMOSO FABULOSO', 'AMMORBIDENTE I CONCENTRATI', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('AMMORBIDENTE VALIDO', 'DETERGENTE VALIDO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('ANANAS SCIROPPO', 'ANANAS A FETTO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('ARACHIDI SGUSCIATE KOME TE', 'ARACHIDI', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('ARROSTO SCELTO DI BOVINO ADULTO', 'TRIPPA DI BOVINO ADULTO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('FETTINE PER GRIGLIA DI BOVINO ADULTO', 'TRIPPA DI BOVINO ADULTO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('FETTINE PER SCALOPPINE DI BOVINO ADULTO', 'TRIPPA DI BOVINO ADULTO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('HAMBURGER DI BOVINO ADULTO', 'TRIPPA DI BOVINO ADULTO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('MACINATA MISTA DI SUINO E BOVINO ADULTO', 'TRIPPA DI BOVINO ADULTO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('MACINATA SCELTA DI BOVINO ADULTO', 'TRIPPA DI BOVINO ADULTO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('POLPETTE DA SUGO MISTO DI BOVINO ADULTO E SUINO', 'TRIPPA DI BOVINO ADULTO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('SPEZZATINO DI BOVINO ADULTO', 'TRIPPA DI BOVINO ADULTO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('STRACCETTI DI BOVINO ADULTO', 'TRIPPA DI BOVINO ADULTO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('TAGLIATA DI BOVINO ADULTO', 'TRIPPA DI BOVINO ADULTO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('ARTICOLI DA BEVANDE', 'BEVANDA DI SOIA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('BEVANDA ALLA FRUTTA', 'BEVANDA DI SOIA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('BEVANDE ALLA FRUTTA ZERO ZUCCHERI', 'BEVANDA DI SOIA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('ASCIUGATUTTO CHRISTMAS', 'ASCIUGATUTTO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('ASCIUGUTUTTO', 'ASCIUGATUTTO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('TAPPETTINI ASSORBENTI PI STOP', 'ASSORBENTI ULTRA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('BAGNO SCHIUMA LATTE E OLIVE', 'DOCශA SCHIUMA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('BAGNOSCHIUMA LUXURY', 'DOCශA SCHIUMA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('BAGNODOCCIA CREMA SPUMA NUTRIENSE', 'SAPONE CREMA SPUMA SCIAMPAGNA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('CONO CINQUE STELLE SAMMONTANA CROCCIANTO', 'BARATTOLINO SUBLIME SAMMONTANA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('BASE PER PIZZA SENZA GLUTINE', 'BASE PER PIZZA STUFFER', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PALA PER PIZZA IN ACCIAIO ALPINA', 'BASE PER PIZZA STUFFER', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('TEGLIA PER PIZZA IN ACCIAIO ALPINA', 'BASE PER PIZZA STUFFER', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('BASTONCINI VERDURE SPINACI', 'PASSATO DI VERDURE', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('BEL PAESE GALBANI', 'CERTOSA GALBANI', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('FORMAGGINI BEL PAESE GALBANI', 'CERTOSA GALBANI', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('BENESSERE TWININGS', 'TÈ TWININGS', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('TÈ VERDE TWININGS', 'TÈ TWININGS', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('GRATTIGIATO ITALIANO GRANAROLO', 'BESCIAMELLA GRANAROLO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PANNA UHT DA CUCINA GRANAROLO', 'BESCIAMELLA GRANAROLO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('BI-SNACK BIRAGHINO CON CARALLI BIRAGHI', 'BIRAGHINI BIRAGHI', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('BIRAGHINI GRAN BIRAGHI', 'BIRAGHINI BIRAGHI', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('BURRO SELEZIONE BIRAGHI', 'BIRAGHINI BIRAGHI', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('GRAN RICOTTA SUPER CREMOSA BIRAGHI', 'BIRAGHINI BIRAGHI', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('SNACK BIRAGHINI BIRAGHI', 'BIRAGHINI BIRAGHI', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('BIBITE COCA COLA FANTA SPRITE', 'COCA COLA CLASSICA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('COCA COLA CLASSICA, COCA COLA ZERO, SPRITE', 'COCA COLA CLASSICA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('COCA COLA CLASSICA, ZERO FANTA CLASSICA', 'COCA COLA CLASSICA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('COCA COLA CLASSICO ZERO', 'COCA COLA CLASSICA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('BIBITE ZERO SAN BENEDETTO', 'BIBITE EPPY', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('BIETA ERBETTA A CUBETTI', 'BIETA ERBETTA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('BILANCIA DIGITALE PESAPERSONE INNOLIVING', 'BILANCIA PESAPERSONE DIGITALE', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('LIQUIDO LAVATRICE TOTAL 4+1 BIO PRESTO', 'BIO PRESTO TOTAL 4+1', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('BIRRA GRAN RISERVA PERONI', 'BIRRA PERONI', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('BIRRA PERONI LAGER', 'BIRRA PERONI', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('BIRRA VAN PUR EXTRA STRONG', 'BIRRA KUMPEL ULTRA STRONG', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('BISCOFITTE SALUTE SENZA OLIO DI PALMA', 'BISCOTTO SALUTE MONVISO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('BISCOTTI ZERO-PIÙ BALOCCO', 'BISCOTTI BALOCCO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('COLOMBA CLASSICA MINI BALOCCO', 'BISCOTTI BALOCCO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('BISCOTTI CLASSICI', 'BISCOTTI NATURA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('BISCOTTI COLUSSI ZUPPALLETTE', 'BISCOTTI COLUSSI', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('BISCOTTI ZUPPALATTE COLUSSI', 'BISCOTTI COLUSSI', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('GRAN VARI COLUSSI MINI BISCOTTI', 'BISCOTTI COLUSSI', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('ZUPPALATTE COLUSSI', 'BISCOTTI COLUSSI', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('BISCOTTI DEL LAGACCIO PANARELLO', 'MESCOLANZA PANARELLO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('BISTECCHINE DI MARE TIKO', 'BISTECHINE DI MARE', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('BOCCONCINI DI MOZZARELLA FIOR DI LATTE', 'MOZZARELLA JULIENNE', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('FIORI DI LATTE BOCCONCINI DI MOZZARELLA', 'MOZZARELLA JULIENNE', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('MOZZARELLA BOCCONCINO LIGHT', 'MOZZARELLA JULIENNE', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('MOZZARELLA FIOR DI LATTE', 'MOZZARELLA JULIENNE', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('MOZZARELLA SANTA LUCIA GALBANI', 'MOZZARELLA JULIENNE', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('MOZZARELLA TRIS SANTA LUCIA', 'MOZZARELLA JULIENNE', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('MOZZARELLA TRIS SANTA LUCIA GALBANI', 'MOZZARELLA JULIENNE', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('SFOGLIA DI MOZZARELLA', 'MOZZARELLA JULIENNE', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('BOCCONCINI IN SALSA PER GATTI BETTIE', 'BOCCONCINI IN SALSA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('BOCCONCINI PER GATTI, PER CANI', 'BOCCONCINI IN SALSA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('CROCCANTINI PER GATTI', 'BOCCONCINI IN SALSA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('BONARDA OLTREPRO PAVESE DOC LE ROVOLE', 'BONARDA DELL''OLTREPO PAVESE DOC', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('BRACIOLE DI COPPA CON OSSO', 'BRACIOLE DI SUINO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('BRESAOLA DI TACCHINO', 'BRESAOLA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('BRESAOLA DI TACCHINO RIGAMONTI', 'BRESAOLA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('BRESAOLA PUNTA D''ANCA IGP RIGAMONTI', 'BRESAOLA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('BRESAOLA VALTELLINA IGP RIGAMONTI', 'BRESAOLA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('CARPACCIO DI BRESAOLA PUGLIA D''ANCA RIGAMONTI', 'BRESAOLA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('CARPACCIO DI BRESAOLA PUNTA D''ANCA', 'BRESAOLA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('CARPACCIO DI BRESAOLA PUNTA D''ANCA RIGAMONTI', 'BRESAOLA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('BRIE PRESIDENT', 'BRIE', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('BUDINO HIGH PROTEIN ALPLI', 'PANCAKES HIGH PROTEIN', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('CREMA CARAMEL HIGH PROTEIN MILK PRO', 'PANCAKES HIGH PROTEIN', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('BURRATA DI BUFALA PONTE REALE', 'BURRATA DI BUFALA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('IL FRESCO SPALHABILES NONNO NANNI', 'BURRATA NONNO NANNI', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('IL FRESCO SPALMABILE NONNO NANNI', 'BURRATA NONNO NANNI', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('ROBIOLA NONNO NANNI', 'BURRATA NONNO NANNI', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('STRACCHINO NONNO NANNI', 'BURRATA NONNO NANNI', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('STRACCIATELLA NONNO NANNI', 'BURRATA NONNO NANNI', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('BURRO BIO PARMAREGGIO', 'BURRO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('BURRO GRANAROLO', 'BURRO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('BURRO PARMAREGGIO', 'BURRO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('BURRO PARMEREGGIO SENZA LATTOSIO', 'BURRO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('CAFFÈ CREMA E GUSTO LAVAZZA CLASSICO', 'CAFFÈ CREMA E GUSTO LAVAZZA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('CAFFÈ QUALITÀ ROSSA LAVAZZA', 'CAFFÈ CREMA E GUSTO LAVAZZA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('CAPSULE LAVAZZA A MODO MIO', 'CAFFÈ IN CAPSULE', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('CAMOMILLA SETACCIATA BONOMELLI', 'CAMOMILLA BIO EVERTON', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('CANDEGGINA PROFUMATA LAVANDA', 'CANDEGGINA CLASSICA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('DISGORGANTE SCALA CON CANDEGGIANA', 'CANDEGGINA CLASSICA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('MIELE DI FIORI AMBROSOLI', 'CANDITI AMBROSOLI', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('CAPRINO DI LATTE DI CAPRA', 'LATTE DI COCCO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('CARAMELLINE DIVERSI TIPI', 'QUASAR DIVERSI TIPI', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('INSALATE DIVERSI TIPI E GRAMMATURE', 'QUASAR DIVERSI TIPI', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('SALSA AMADORI DIVERSI TIPI', 'QUASAR DIVERSI TIPI', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('CARTA IGIENICA CLASSICA', 'CARTA IGIENICA BRAVO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('CARTA IGIENICA FAMILY SCOTTEX', 'CARTA IGIENICA BRAVO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('CARTA IGIENICA LALYNEA', 'CARTA IGIENICA BRAVO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('CARTA IGIENICA PULITO COMPLETO SCOTTEX', 'CARTA IGIENICA BRAVO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('CARTA IGIENICA TENDERLY GRAN ROTOLO', 'CARTA IGIENICA BRAVO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('CARTA IGIENICA THAT''S AMORE', 'CARTA IGIENICA BRAVO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('CARTELLINA ELASTICO FANTASIE ASSORTITE', 'MISTO FANTASIE LA SUISSA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('T BABYS TOGVAGLIOLI FANTASIE ASSORTITE', 'MISTO FANTASIE LA SUISSA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('CHE SQU'' DI BIFFI', 'CHE SUGO! BIFFI', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('CIAMBELLA YOGURT LIMONE VANIGLIA', 'CIAMBELLA ZUCCHERATA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('CROCCHETTE PER CANI PRIMIUM', 'CIBO PER CANI PRIMIUM', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('CIBO PER GATTI HOLISTIC ALMO NATURE', 'CIBO PER GATTI SIMBA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('LETTIERA PER GATTI AL NATURE', 'CIBO PER GATTI SIMBA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('CICORIA FOGLIA A FOGLIA', 'CICORIA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('CIOCCOLATINI ZAINI', 'CIOCCOLATI NOVI', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('CIOCCOLATO LATTE FONDENTE', 'CIOCCOLATI NOVI', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('CIOCCOLATO NOVIPÙ', 'CIOCCOLATI NOVI', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PRALINA CIOCCOLATO RIPIENO', 'CIOCCOLATI NOVI', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('CIOCCOLATINI ASSORTITI PIACERI INFINITI MONARDO', 'KEFIR ASSORTITI', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('GELATO GUSTI ASSORTITI', 'KEFIR ASSORTITI', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('GHIACCIOLI ASSORTITI', 'KEFIR ASSORTITI', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('GIOCHI ASSORTITI BIMBO CHICCO', 'KEFIR ASSORTITI', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('LA CROSTATA CASALINGA GUSTI ASSORTITI', 'KEFIR ASSORTITI', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('OVETTI DI CIOCCOLATO ASSORTITI', 'KEFIR ASSORTITI', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('TOVAGLIA COLORI ASSORTITI', 'KEFIR ASSORTITI', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('CIUFFETTI DI SPINACI PRIMAVERA FINDUS', 'SOFFICINI FINDUS', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PISELLINI PRIMAVERA FINDUS', 'SOFFICINI FINDUS', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('CLEMENTINE CASSETTA', 'CLEMENTINE', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('GHIOTTINE COCKTAIL DI GAMBERI', 'COCKTAIL DI MAZZANCOLLE', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('COMPOSTA LA FRUTTA ITALIANA BOSCHETTI', 'PIATTI COMPOSTABILI', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('CONCIME LIQUIDO PIANTE FIORITE UNIVERSALE', 'TERRICCIO UNIVERSALE', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('GUANTI SUPER UNIVERSAL', 'TERRICCIO UNIVERSALE', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('CONFETTURA DI FRUTTA VIRTÙ BIO OROGEL', 'CONFETTURA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('CONFETTURA VIRTU DI FRUTTA BIO OREGEL', 'CONFETTURA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('CONFEZIONE BARDI CARESSE', 'CONFEZIONE DAHLIA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('CONFEZIONE PELUCHE WITOR''S', 'CONFEZIONE DAHLIA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('VASCHETTE IN CARTONCINO CON COPPERCHI CUKI', 'CONTENITORI IN CARTONCINO CUKI', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('CONTORNO GHIOTTO CON VERDURE GRIGLIATE', 'CONTORNO PATATE', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('CONTORNO PATATE, ZUCCHINE E CIPOLLA', 'CONTORNO PATATE', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('GELATO COPPA CAFFÈ', 'COPPA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('COPPA DI SUINO PER ARROSTO', 'COSCIA DI SUINO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('GRIGLIATA MISTA DI SUINO', 'COSCIA DI SUINO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('LONZA DI SUINO A TRANCI', 'COSCIA DI SUINO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('SPIEDINI DI SUINO', 'COSCIA DI SUINO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('COSCIOTTO DI POLLO', 'FUSELLI DI POLLO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PETTO DI POLLO GRIGLIATO IN GELATINA', 'FUSELLI DI POLLO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('ROLATINE DI POLLO', 'FUSELLI DI POLLO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('COTECHINO COTTO DI MODENA IGP', 'COTECHINO COTTO MODENA IGP', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('CRACKERS COLUSSI', 'CRACKERS MISURA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('CRACKERS COLUSSI SALATI', 'CRACKERS MISURA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('CREMA DI YOGURT MÜLLER', 'MIX MÜLLER', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('YOGURT BIANCO MIX MÜLLER', 'MIX MÜLLER', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('CREMA DI ZUCCHETTA', 'CREMA NOVI', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('CRENA VEGETALE DA CUCINA', 'CREMA VEGETALE DA CUCINA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PURÈ DI PATATE CON LATTE PFANNI', 'CROCCHETTE DI PATATE', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PATÉ PER GATTI STERILISED LECHAT', 'CROCCHETTE PER GATTI LECHAT', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('YAKISOBA CLASSICO', 'CRODINO CLASSICO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('MAGNUM ALGIDA CLASSIC ALMOND', 'CUCCIOLONE CLASSICO ALGIDA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('CUORI DI FILETTI DI SALMONE SELVAGGIO', 'FILETTI DI SALMONE', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('TARTINE SALMONE E GAMBERETTI', 'FILETTI DI SALMONE', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('TARTINE SALMONE E GAMBERI', 'FILETTI DI SALMONE', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('FILETTI DI MERLUZZO', 'CUORI DI MERLUZZO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('FILETTI DI MERLUZZO ALASKA', 'CUORI DI MERLUZZO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('DADO KNORR VEGETALE-CLASSICO', 'DADI CLASSICO VEGETALE', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('IL DADO KNORR VEGETALE', 'DADI CLASSICO VEGETALE', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('DANACOL DANONE BIANCO', 'HIPRO DANONE', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('DENTIFRICIO AQUAFRESH', 'DENTIFRICIO AZ', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('DENTIFRICIO SENSODYNE', 'DENTIFRICIO AZ', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('DENTIFRICIO TRIPLA PROTEZIONE AQUAFRESH', 'DENTIFRICIO AZ', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('DEODORANTE NIVEA', 'DEODORANTE DOVE', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('DEODORANTE ROLL-ON DOVE', 'DEODORANTE DOVE', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('DETERGENTE INTIMO', 'DETERGENTE', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('DETERGENTE INTIMO NEUTROMED', 'DETERGENTE', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('DETERGENTE INTIMO SENSITIVE CHILLY', 'DETERGENTE', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('DETERGENTE SPRAY', 'DETERGENTE', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('ECODETERGENTE PIATTI VERI', 'DETERGENTE', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('EXTRA POWER CHANTE CLAIR', 'DETERGENTE CHANTE CLAIR', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('LINEA CHANTE CLAIR, CHANTE CLAIR VEST', 'DETERGENTE CHANTE CLAIR', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('LIQUIDO PER LAVATRICE CHANTE CLAIR', 'DETERGENTE CHANTE CLAIR', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('DETERGENTE INTIME FELICE AZZURRA', 'LAVATRICE FELCE AZZURRA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('DETERGENTE LIQUIDO PULITO & IGIENE DIXAN', 'DETERSIVO LIQUIDO DIXAN CLASSICO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('LIQUIDO LAVATRICE DIXAN CLASSICO', 'DETERSIVO LIQUIDO DIXAN CLASSICO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('DETERSIVO LAVATRICE SPUMA DI SCIAMPAGNA MARSIGLIA', 'DETERGIVO LAVATRICE MARSIGLIA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('DETERSIVO LAVATRICE SPUMA E CAMPAGNA MARSIGLIA', 'DETERGIVO LAVATRICE MARSIGLIA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('FOGLIETTI PER ASCIUGATRICE SPUMA DI SCIAMPAGNA', 'DETERGIVO LAVATRICE MARSIGLIA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('DETERSIVO PER BUCATO ARIETE', 'DETERSIPI PIATTI CIF', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('DETERSIVO PER PIATTI', 'DETERSIPI PIATTI CIF', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('DETERSIVO PIATTI PROFUMAZIONI', 'DETERSIPI PIATTI CIF', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('DETERVISO PER LAVATRICE DETRINO', 'ECONIRICORA LAVATRICE VEST', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PANDOLCE PRETI', 'DOLCE PASQUA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('DOLCETTO DI OVADA DOC', 'DOLCETTO D''ACQUI DOC', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('ERBETTE PRONTO CUOCI KOME TE', 'ZUPPE KOME TE', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('LINEA ZUPPE KOME TE', 'ZUPPE KOME TE', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('FAGOLOSI GRISSIN BON CLASSICI', 'FAGOLOSI GRISSIN BON', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('FAZZOLETTI SCOTTEX', 'FAZZOLETTI', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('FETTE DI COTECHINO SENZA GLUTINE', 'FROLLINI SENZA GLUTINE', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('FILETTI DELICIUS DI SGOMBRO', 'TRANCHIO DI SGOMBRO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('FILETTI DI SGOMBRO ANGELO PARODI', 'TRANCHIO DI SGOMBRO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('FILETTI DI SGOMBRO DELICIUS', 'TRANCHIO DI SGOMBRO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('FILETTI DI ALICI DEL MAR CANTABRICO RIZZOLI', 'FILETTI DI ALICI DELICIUS PIZZA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('FILETTI DI ALICI DISTESE DELICIUS', 'FILETTI DI ALICI DELICIUS PIZZA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('FILETTI DI ALICI IN OLIO DI OLIVA DELICIUS', 'FILETTI DI ALICI DELICIUS PIZZA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('FILETTI DI ALICI IN OLIO DI SEMI', 'FILETTI DI ALICI DELICIUS PIZZA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('FILETTI DI ALICI L''OLIO DI OLIVA DELICATESSEN', 'FILETTI DI ALICI DELICIUS PIZZA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('FILETTI DI TONNO MAREBLU', 'TONNO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('FILETTI DI TONNO MARUZELLA', 'TONNO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('FILETTI DI TONNO NOSTROMO', 'TONNO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('TRANCETTI DI TONNO RIO MARE', 'TONNO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('FIOCCHINI DI AVENA INTEGRALE', 'FIOCCHI DI LATTE', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('FIOR DI FRUTTA BIO RIGONI DI ASIAGO', 'POLPA DI FRUTTA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('POPPURRI DI FRUTTA BIO VALFRUTTA', 'POLPA DI FRUTTA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('SUCCO DI FRUTTA', 'POLPA DI FRUTTA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('SUCCO E POLPA DI FRUTTA', 'POLPA DI FRUTTA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('FONTAL NATIONALE', 'FONTAL ESTERO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('FORMAGGI ALTOPRATO', 'FORMAGGINO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('FORMAGGINI TIGRE', 'FORMAGGINO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('FORMAGGIO GRECO', 'FORMAGGINO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('FORMAGGIO GRECO MERAKI', 'FORMAGGINO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('FRIGGÌ TOPAZIO', 'FRIGGI TOPAZIO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('FRUTTA SECCA SGUSCIATA KOME TE', 'FRUTTA SECCA E SNACK KOME TE', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('FRUTTOLO NESTLÉ', 'NESQUIK NESTLÉ', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('MINI KITKAT NESTLÉ', 'NESQUIK NESTLÉ', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('VANILLINA', 'GALLINA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('GAMBERO INDOPACIFICO SGUCCIATO', 'GAMBERETTI BOREALI SGUCCIATI', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('GAMBERO INDOPACIFICO SGUSCIATO', 'GAMBERETTI BOREALI SGUCCIATI', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('GAMBERI ARGENTINI SQUASCIATI', 'GAMBERI ARGENTINI SELVAGGI', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('LINGUE CROCCANTI FORINO DAMIANI', 'GELATO CROCCANTINO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('LINEA GLISS SCHWARZKOPF', 'GLISS SCHWARZKOPF', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('GNOCCHI ALLA BARBABIETOLA', 'GNOCCHI ALLA ROMANA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('GNOCCHI ALLA RUCOLA', 'GNOCCHI ALLA ROMANA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('GORGONZOLA DOLCE DOP AL CUCCHIAIO', 'GORGONZOLA DOP DOLCE', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('GORGONZOLA DOP BIG IOOR', 'GORGONZOLA DOP DOLCE', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('GORGONZOLA DOP DOLCE GIM INVERNIZZI', 'GORGONZOLA DOP DOLCE', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('GORGONZOLA DOP E MASCARPONE', 'GORGONZOLA DOP DOLCE', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('GRAN BIRAGHI GRATTUGGIATO FRESCO', 'GRANA PADANO DOP FERRARI', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('GRAN PECORINO GRATTUGIATO', 'GRANA PADANO DOP FERRARI', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('GRANA PADANO DOP GRATTUGIATO FRESCO', 'GRANA PADANO DOP FERRARI', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('GRANA PADANO RISERVA DOP GRATTUGIATO FRESCO FERRARI', 'GRANA PADANO DOP FERRARI', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('GRANMIX CUCINA GRATTUGIATO FRESCO FERRARI', 'GRANA PADANO DOP FERRARI', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('GRATTUGIATO FRESCO GRAN BIRAGHI', 'GRANA PADANO DOP FERRARI', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('GRAN COPPA FAMIGLIA TOMRITTO', 'GRAN COPPA FAMIGLIA TONITTO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('MINI COPPA FAMIGLIA TOMITTO', 'GRAN COPPA FAMIGLIA TONITTO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('GRANMISTO DI FUNGHI CON PORCINI', 'POLENTA FUNGHI FORMAGGIO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('POLENTA PRONTA CON FORMAGGI CON FUNGHI', 'POLENTA FUNGHI FORMAGGIO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('GRIGLIA PRONTA PER BARBECUE RAPIDO', 'GRIGLIA PER BARBECUE', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('ICE 3 CUP', 'ICE CUP', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('IL MIO GRAN RAGÙ STAR', 'IL MIO BRODO STAR', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('INSALATA CON TONNO ACTIVE PRO MAREBLU', 'INSALATE PLANT POWER MAREBLU', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('INSALATA DI MARE', 'INSALATONA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('INSALATA KOMETE', 'INSALATONA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('LE INSALATE', 'INSALATONA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('MOZZARELLE MOZARI INVERNIZZI', 'INVERNIZZINA INVERNIZZI', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('STRACCHINO INVERNIZZINA INVERNIZZI', 'INVERNIZZINA INVERNIZZI', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('KETCHUP TOP DOWN CALVÉ', 'KETCHUP CALVÉ', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('KINDER BUENO', 'KINDER MAXI', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('KINDER FETTA AL LATTE', 'KINDER MAXI', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('KRAPFEN ALLA CREMA', 'KRAPFEN CREMA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('L''ABC DELLA MERENDA TENERONI GRAN TERE', 'L''ABC DELLA MERENDA PARMAGREGGIO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('L''ACCHIAPPACOLORI GREY', 'L''ACCHIAPPACOLORE GREY', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('L''ORIGINALE PINSA ROMANA NUVOLA', 'PINSA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('LA MINI PINSA ROMANA', 'PINSA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('LA MINI PINSA ROMANA L''ARTIGIANO', 'PINSA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('LA PASSATA DI POMODORO', 'POLPA DI POMODORO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PASSATA DI POMODORO AGRONMENTE', 'POLPA DI POMODORO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PASSATA DI POMODORO MUTTI', 'POLPA DI POMODORO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('POLPA PRONTA DI POMODORO', 'POLPA DI POMODORO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('SALSA DI POMODORO CILIEGINO', 'POLPA DI POMODORO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('LATTE UHT ALTA DIGERIBILITÀ SENZA LATTOSIO ZYMIL PARMALAT', 'LATTE LITE ALTA DIGERIBILITA CANDIA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('LATTE UHT ALTA DIGERIBILITÀ ZYMIL PARMALAT', 'LATTE LITE ALTA DIGERIBILITA CANDIA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('LATTE UHT 100% ITALIANO BIRAGHI', 'LATTE UHT', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('LATTE UHT INTERO', 'LATTE UHT', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('LATTE UMM SENZA LATTOSIO ACCADI GRANAROLO', 'LATTE UHT ACCADI SENZA LATTOSIO GRANAROLO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('LATTE UHT CANNABIS PARZIALMENTE SCREMATO', 'LATTE UHT PARZIALMENTE SCREMATO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('LATTE UNH PARZIALMENTE SCREMATO', 'LATTE UHT PARZIALMENTE SCREMATO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PASTIGLIE LAVASTOVIGLIE PRIL', 'LAVASTIGLIE SVELTO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('POWER GEL LAVASTOVIGLIE ALL IN 1 FINISH', 'LAVASTIGLIE SVELTO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('LE PROSCIUTTINE CLASSICHE, FORMAGGIO', 'PATATINE CLASSICHE FINOUS', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('LE SFOGLIE GRAN PAVESI', 'RINGO PAVESI', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PAVESINI PAVESI', 'RINGO PAVESI', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('LIGNINO OMINO BIANCO', 'VINO ROSSO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('VINO BIANCO BRIK', 'VINO ROSSO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('VINO BIANCO CASTELLI ROMANI DOC', 'VINO ROSSO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('VINO BIANCO ROSSO', 'VINO ROSSO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('SORBETTO AL LIMONE', 'LIMONI', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('SORBETTO LIMONE TONITTO', 'LIMONI', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('SUCCO DI LIMONI SICILIANI LIMMI', 'LIMONI', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('ROBIOLA OSELLA', 'LINEA OSELLA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('MAIONESE BIOLOGICA BIFI', 'MAIONESE BIFFI', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('MAIONESE CALVÉ', 'MAIONESE BIFFI', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('MAIONESE CALVÉ CLASSICA', 'MAIONESE BIFFI', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('MAIONESE CLASSICA CALVÉ', 'MAIONESE BIFFI', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('SALSA CALVÉ MAIONESE', 'MAIONESE BIFFI', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('MASCARPONE ACCADI GRANAROLO', 'MASCARPONE', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('MELE GOLDEN', 'PRIL GOLD', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('MINESTRONE CON LEGUMI', 'MINESTRONE MIOORTO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('SALAMINI BERETTA CLASSICO', 'MINI DIGESTIVE CLASSIC', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('MISTO PER RISOTTO E SPAGHETTI APPETTAIS', 'RISO PER RISOTTO SCOTTI', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('MORTADELLA BOLOGNA IGP CON PISTACCHI', 'MORTADELLA INTERA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('MÜLLER THURGAU TREVENEZIE IGT', 'SAUVIGNON TREVENEZIE IGT', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('OLIVE VERDI DENOCCHIOLATE OLIOVÌ SACLÀ', 'OLIVE NERE HALKIDIKI DENOCCIOLATE', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('SALMONE SCOZZESE AFFUMICATO', 'PANCETTA DOLCE AFFUMICATA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('SANDWICH ALTO PROTEICO IBIS', 'PANE PROTEICO PEMA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PANNO PAVIMENTI COTONE-MICROFIBRA', 'PANNO PAVIMENTI UMIDIFICATO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PASTA DI SEMOLA BARILLA', 'PASTA DI SEMOLA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PASTA DI SEMOLA CORTICELLA', 'PASTA DI SEMOLA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PASTA DI SEMOLA DI GRANO DURO BIOLOGICO', 'PASTA DI SEMOLA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PASTA DI SEMOLA FORMATI NORMALI', 'PASTA DI SEMOLA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PASTA DI SEMOLA VOIELLO', 'PASTA DI SEMOLA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PASTA FRESCA ORECCHETTE TROFIE', 'RICOTTA FRESCA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PASTA FRESCA RIPIENA', 'RICOTTA FRESCA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PASTA FRESCA SFOGLIA', 'PASTA SFOGLIA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PASTA SFOGLIA ROTONDA', 'PASTA SFOGLIA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PASTA SFOGLIA STUFFER', 'PASTA SFOGLIA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PASTA SFOGLIA VEGETALE STUFFER', 'PASTA SFOGLIA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PIADA SFOGLIATA', 'PASTA SFOGLIA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('SFOGLIATINE DOLCI', 'PASTA SFOGLIA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PASTA PROTEIN DALLA COSTA', 'PROTEIN KREAM', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PESCHE GIALLE', 'PATATE GIALLE', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PESCHE NETTARINE GIALLE', 'PATATE GIALLE', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PESCHE PARAGUAY GIALLE', 'PATATE GIALLE', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PEPERONI ROSSI, GIALLI', 'PEPERONATA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PESCHE ITALIANE ALLO SCIROPPO', 'PESCHE BIANCHE', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PESCHE SCI ROPPATE', 'PESCHE BIANCHE', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PESTO BARILLA', 'RAGÙ BARILLA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('SUGO BARILLA BASILICO ARRABBIATA', 'RAGÙ BARILLA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PHILADELPHIA CLASSICO', 'PHILADELPHIA LIGHT', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PHILADELPHIA ORIGINAL', 'PHILADELPHIA LIGHT', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PIATTI PRONTI ASIA MIA', 'PIATTI PRONTI KNORR', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PIATTI PRONTI DI PESCE', 'PIATTI PRONTI KNORR', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PIATTI PRONTI MINESTRONE KNORR', 'PIATTI PRONTI KNORR', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PIZZA MARGHERITA APPETAIS', 'PIZZA MARGHERITA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PIZZA MARGHERITA BELLA NAPOLI BUITONI', 'PIZZA MARGHERITA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PIZZA MARGHERITA CROCCANTE E SOTTILE', 'PIZZA MARGHERITA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('TENTACOLO DI POLPO COTTO', 'POLPO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('POMODORI A GRAPPOLO', 'POMODORI DATTERINO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('POMODORI DATTERINO CASSETTA', 'POMODORI DATTERINO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('POMODORI PERINI DA INSALATA', 'POMODORI DATTERINO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('POMODORI PERINI INSALATARI', 'POMODORI DATTERINO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('POMODORI PERINO INSALATARI', 'POMODORI DATTERINO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('POMODORI PICCADILLY', 'POMODORI DATTERINO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('POMODORINI DATTERINO TRIPFOGLIO', 'POMODORI DATTERINO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PREPARATO PER DOLCI PANNA COTTA', 'PREPARATO PER BUDINO S.MARTINO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PREPARATO PER PIZZA ISTANTANEA', 'PREPARATO PER BUDINO S.MARTINO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PREPARATO PER TORTA CHEESECAKE CAMEO', 'PREPARATO PER BUDINO S.MARTINO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PRIMI PRONTI LASAGNE CANNELLONI MELANZANE', 'PRIMI PRONTI', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PRIMI PRONTI LASAGNE, CANNELLONI, MELANZANE', 'PRIMI PRONTI', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PROFUMATORE SGRASSATORE LUXURY', 'SGRASSATORE UNIVERSALE', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('SGRASSATORE CHANTE CLAIR', 'SGRASSATORE UNIVERSALE', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('SGRASSATORE UNIVERSALE CHANTE CLAIR', 'SGRASSATORE UNIVERSALE', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PROSCIUTTO COTTO ALTA QUALITÀ', 'PROSCIUTTO CRUDO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PROSCIUTTO COTTO ALTA QUALITÀ NAZIONALE LENTI', 'PROSCIUTTO CRUDO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PROSCIUTTO COTTO ALTA QUALITÀ RICCAFETTA RASPINI', 'PROSCIUTTO CRUDO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PROSCIUTTO COTTO DI ALTA QUALITÀ ROVAGNATI', 'PROSCIUTTO CRUDO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PROSCIUTTO COTTO SCELTO CUOR DI GUSTO LENTI', 'PROSCIUTTO CRUDO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PROSCIUTTO CRUDO DI PARMA DOP', 'PROSCIUTTO CRUDO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PROSCIUTTO CRUDO NAZIONALE', 'PROSCIUTTO CRUDO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PROSCIUTTO CRUDO SAN DANIELE DOP', 'PROSCIUTTO CRUDO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PROSCIUTTO DI PARMA DOP', 'PROSCIUTTO CRUDO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PROSCIUTTO SAN DANIELE DOP', 'PROSCIUTTO CRUDO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('TENERONI GRAN TERRE PROSCIUTTO COTTO', 'PROSCIUTTO CRUDO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('PROSECCO DOC FRIZZANTE', 'PROSECCO DOC EXTRA DRY', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('SACCHETTI RIFIUTI PROFUMATI', 'SACCO PRATICO VIROSAC', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('SACCO RIFIUTI VIROSAC', 'SACCO PRATICO VIROSAC', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('SALAME GENTILE DELLA ROSA GRAN CRUDO', 'SALAME GENTILE DELLA ROSA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('SALLUMI SENETER', 'SALUMI SENFTER', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('SALSICCIA DI MAIALE', 'SALSICCIA PICCANTE', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('SALUMI EKOM DIVERSI TIPI', 'SALUMI EKOM', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('SALVIETTE BABY CON COPERCHIO', 'SALVIETTE BABY', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('SALVIETTE BABY FRESH', 'SALVIETTE BABY', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('SALVIETTE BABY FRESH POP-UP', 'SALVIETTE BABY', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('SALVIETTE HUGGIES UNISTAR', 'SALVIETTE BABY', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('SCOPA DA ESTERNI E GIARDINO', 'SET ATTREZZI DA GIARDINO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('SFILACCI DI BRESSOLA VIAGGIO NEL GUSTO', 'SULACCI DI BRESCİA VIAGGIO NEL GUSTO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('SFOGLIA EXTRAFINE PER LASAGNE', 'ZUCCHERO BIANCO EXTRAFINO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('SHAMPOO FRUCTIS GARNIER', 'ULTRADOLCE GARNIER', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('SHAMPOO ULTRADOLCE GARNIER', 'ULTRADOLCE GARNIER', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('SPUNTI SIMMENTHAL', 'SIMMENTHAL', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('SNACK GHOST IS BACK ON HAPPY HALLOWEEN GECHELLE', 'TORTA MONSTER CAKE HAPPY HALLOWEEN GECHELLE', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('SPECK DELL''ALTO ADIGE IGP', 'SPECK ALTO ADIGE IGP', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('SPINACI IN CUBI', 'SPINACI GUSTOSI', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('SPUGNE VILEDA', 'SPUGNA VILEDA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('TURBO SMART VILEDA', 'SPUGNA VILEDA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('SPUMANTE BRUT DOLCE CUVÉE', 'VINO SPUMANTE BRUT ROSE', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('SPUMANTE MÜLLER THURGAU CASCINE DI CORTE EXTRA DRY', 'SPUMANTE MÜLLER THURGAU', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('STELI GUSTOSI MIOORTO', 'YOGURT GUSTO-GUSTO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('STELI GUSTOSI MIORTO', 'YOGURT GUSTO-GUSTO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('SUGO PRONTO ALLFRUTTI DI MARE ROSSO ALLE COZZE', 'SUGHI PRONTI FRUTTI DI MARE', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('SUGO ALLA MARINARA APPETAIS', 'SUGO SCOGLIO APPETAIS', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('SUGO ALLO SCOGLIO APPETTAIS', 'SUGO SCOGLIO APPETAIS', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('T OVAGLIOLI BRAVO', 'TAVOGLIOLI', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('TAVOGLIOLI MONOVELO BRAVO', 'TAVOGLIOLI', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('TONAGIOLI BRAVO', 'TAVOGLIOLI', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('TORRONCINI VERGANI', 'TORRONE', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('TORRONE ALLE MANDORLE VERGANI', 'TORRONE', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('TOVAGLIOLI DECORATI EVERY', 'TOVAGLIOLI', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('TOVAGLIOLI DI CARTA', 'TOVAGLIOLI', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('TOVAGLIOLI DOPPIO VELO', 'TOVAGLIOLI', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('TOVAGLIOLI MONOVELO SCOTTEX', 'TOVAGLIOLI', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('VASCHETTA GELATO CREMA E CAFFÈ VANIGLIA E CACAO', 'VASCHETTA GELATO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('VASO DI FIORI CON GANCINI', 'VASO DA FIORI', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('VELLUTATA PRONTA KNORR', 'ZUPPA PRONTA KNORR', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('VONGOLE SGUSCIATE APPETAIS', 'VONGOLE COTTE CON GUSCIO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('WÜRSTEL DI POLLO E TACCHINO', 'WÜRSTEL', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('WÜRSTEL MISTO', 'WÜRSTEL', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('WÜRSTEL SENZA PELLE', 'WÜRSTEL', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('YOGURT ASSORTITI ALLA FRUTTA VIPRENO', 'YOGURT DA BERE ALLA FRUTTA', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('YOGURT INTERO BIO DA LATTE FIENO VIPITENO', 'YOGURT VIPITENO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('ZUCCHERO DI CANNA BIOLOGICO BIO SWEET', 'ZUCCHERO AL VELO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('ZUCCHERO GREZZO DI CANNA', 'ZUCCHERO AL VELO', 0.85);
INSERT INTO product_aliases (alias_name, canonical_name, similarity_score) VALUES ('ZUPPA DI PESCE', 'ZUPPA DI FARRO', 0.85);
